[package]
name = "web_server"
version = "0.1.0"
authors = ["jlyneu <jly@ccs.neu.edu>"]

[dependencies]
spin = "0.3.5"
num_cpus = "0.2"
chrono = "0.2"
rand = "0.3.14"
docopt = "0.6"
rustc-serialize = "0.3"

[lib]
name = "concurrent_hashmap"
path = "rust-concurrent-hashmap/src/lib.rs"
